/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdventureRouteImport } from './routes/adventure'
import { Route as ConsentRouteImport } from './routes/consent'
import { Route as DoomRouteImport } from './routes/doom'
import { Route as GuestbookRouteImport } from './routes/guestbook'
import { Route as MeRouteImport } from './routes/me'
import { Route as NowRouteImport } from './routes/now'
import { Route as OsRouteImport } from './routes/os'
import { Route as PlaygroundRouteImport } from './routes/playground'
import { Route as RacerRouteImport } from './routes/racer'
import { Route as ResumeRouteImport } from './routes/resume'
import { Route as TerminalRouteImport } from './routes/terminal'
import { Route as DotwellKnownOauthAuthorizationServerRouteImport } from './routes/[.]well-known.oauth-authorization-server'
import { Route as DotwellKnownOpenidConfigurationRouteImport } from './routes/[.]well-known.openid-configuration'
import { Route as AdventureIdRouteImport } from './routes/adventure.$id'
import { Route as ApiAdventureRouteImport } from './routes/api.adventure'
import { Route as ApiChatRouteImport } from './routes/api.chat'
import { Route as ApiGuestbookRouteImport } from './routes/api.guestbook'
import { Route as ApiMcpRouteImport } from './routes/api.mcp'
import { Route as ApiResumeRouteImport } from './routes/api.resume'
import { Route as IngestSplatRouteImport } from './routes/ingest.$'
import { Route as PlaygroundRunRouteImport } from './routes/playground.$run'
import { Route as RacerRunRouteImport } from './routes/racer.$run'
import { Route as ApiAdventureVoiceRouteImport } from './routes/api.adventure.voice'
import { Route as ApiAuthSplatRouteImport } from './routes/api.auth.$'
import { Route as ApiGithubContributionsRouteImport } from './routes/api.github.contributions'
import { Route as DotwellKnownOauthAuthorizationServerApiAuthRouteImport } from './routes/[.]well-known.oauth-authorization-server.api.auth'
import { Route as DotwellKnownOauthProtectedResourceApiMcpRouteImport } from './routes/[.]well-known.oauth-protected-resource.api.mcp'
import { Route as ApiAuthDotwellKnownOpenidConfigurationRouteImport } from './routes/api.auth.[.]well-known.openid-configuration'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdventureRoute = AdventureRouteImport.update({
  id: '/adventure',
  path: '/adventure',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsentRoute = ConsentRouteImport.update({
  id: '/consent',
  path: '/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const DoomRoute = DoomRouteImport.update({
  id: '/doom',
  path: '/doom',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestbookRoute = GuestbookRouteImport.update({
  id: '/guestbook',
  path: '/guestbook',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const NowRoute = NowRouteImport.update({
  id: '/now',
  path: '/now',
  getParentRoute: () => rootRouteImport,
} as any)
const OsRoute = OsRouteImport.update({
  id: '/os',
  path: '/os',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundRoute = PlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const RacerRoute = RacerRouteImport.update({
  id: '/racer',
  path: '/racer',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeRoute = ResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminalRoute = TerminalRouteImport.update({
  id: '/terminal',
  path: '/terminal',
  getParentRoute: () => rootRouteImport,
} as any)
const DotwellKnownOauthAuthorizationServerRoute =
  DotwellKnownOauthAuthorizationServerRouteImport.update({
    id: '/.well-known/oauth-authorization-server',
    path: '/.well-known/oauth-authorization-server',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotwellKnownOpenidConfigurationRoute =
  DotwellKnownOpenidConfigurationRouteImport.update({
    id: '/.well-known/openid-configuration',
    path: '/.well-known/openid-configuration',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdventureIdRoute = AdventureIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdventureRoute,
} as any)
const ApiAdventureRoute = ApiAdventureRouteImport.update({
  id: '/api/adventure',
  path: '/api/adventure',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGuestbookRoute = ApiGuestbookRouteImport.update({
  id: '/api/guestbook',
  path: '/api/guestbook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpRoute = ApiMcpRouteImport.update({
  id: '/api/mcp',
  path: '/api/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiResumeRoute = ApiResumeRouteImport.update({
  id: '/api/resume',
  path: '/api/resume',
  getParentRoute: () => rootRouteImport,
} as any)
const IngestSplatRoute = IngestSplatRouteImport.update({
  id: '/ingest/$',
  path: '/ingest/$',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundRunRoute = PlaygroundRunRouteImport.update({
  id: '/$run',
  path: '/$run',
  getParentRoute: () => PlaygroundRoute,
} as any)
const RacerRunRoute = RacerRunRouteImport.update({
  id: '/$run',
  path: '/$run',
  getParentRoute: () => RacerRoute,
} as any)
const ApiAdventureVoiceRoute = ApiAdventureVoiceRouteImport.update({
  id: '/voice',
  path: '/voice',
  getParentRoute: () => ApiAdventureRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubContributionsRoute = ApiGithubContributionsRouteImport.update({
  id: '/api/github/contributions',
  path: '/api/github/contributions',
  getParentRoute: () => rootRouteImport,
} as any)
const DotwellKnownOauthAuthorizationServerApiAuthRoute =
  DotwellKnownOauthAuthorizationServerApiAuthRouteImport.update({
    id: '/api/auth',
    path: '/api/auth',
    getParentRoute: () => DotwellKnownOauthAuthorizationServerRoute,
  } as any)
const DotwellKnownOauthProtectedResourceApiMcpRoute =
  DotwellKnownOauthProtectedResourceApiMcpRouteImport.update({
    id: '/.well-known/oauth-protected-resource/api/mcp',
    path: '/.well-known/oauth-protected-resource/api/mcp',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthDotwellKnownOpenidConfigurationRoute =
  ApiAuthDotwellKnownOpenidConfigurationRouteImport.update({
    id: '/api/auth/.well-known/openid-configuration',
    path: '/api/auth/.well-known/openid-configuration',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/adventure': typeof AdventureRouteWithChildren
  '/consent': typeof ConsentRoute
  '/doom': typeof DoomRoute
  '/guestbook': typeof GuestbookRoute
  '/me': typeof MeRoute
  '/now': typeof NowRoute
  '/os': typeof OsRoute
  '/playground': typeof PlaygroundRouteWithChildren
  '/racer': typeof RacerRouteWithChildren
  '/resume': typeof ResumeRoute
  '/terminal': typeof TerminalRoute
  '/.well-known/oauth-authorization-server': typeof DotwellKnownOauthAuthorizationServerRouteWithChildren
  '/.well-known/openid-configuration': typeof DotwellKnownOpenidConfigurationRoute
  '/adventure/$id': typeof AdventureIdRoute
  '/api/adventure': typeof ApiAdventureRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/api/guestbook': typeof ApiGuestbookRoute
  '/api/mcp': typeof ApiMcpRoute
  '/api/resume': typeof ApiResumeRoute
  '/ingest/$': typeof IngestSplatRoute
  '/playground/$run': typeof PlaygroundRunRoute
  '/racer/$run': typeof RacerRunRoute
  '/api/adventure/voice': typeof ApiAdventureVoiceRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/github/contributions': typeof ApiGithubContributionsRoute
  '/.well-known/oauth-authorization-server/api/auth': typeof DotwellKnownOauthAuthorizationServerApiAuthRoute
  '/.well-known/oauth-protected-resource/api/mcp': typeof DotwellKnownOauthProtectedResourceApiMcpRoute
  '/api/auth/.well-known/openid-configuration': typeof ApiAuthDotwellKnownOpenidConfigurationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/adventure': typeof AdventureRouteWithChildren
  '/consent': typeof ConsentRoute
  '/doom': typeof DoomRoute
  '/guestbook': typeof GuestbookRoute
  '/me': typeof MeRoute
  '/now': typeof NowRoute
  '/os': typeof OsRoute
  '/playground': typeof PlaygroundRouteWithChildren
  '/racer': typeof RacerRouteWithChildren
  '/resume': typeof ResumeRoute
  '/terminal': typeof TerminalRoute
  '/.well-known/oauth-authorization-server': typeof DotwellKnownOauthAuthorizationServerRouteWithChildren
  '/.well-known/openid-configuration': typeof DotwellKnownOpenidConfigurationRoute
  '/adventure/$id': typeof AdventureIdRoute
  '/api/adventure': typeof ApiAdventureRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/api/guestbook': typeof ApiGuestbookRoute
  '/api/mcp': typeof ApiMcpRoute
  '/api/resume': typeof ApiResumeRoute
  '/ingest/$': typeof IngestSplatRoute
  '/playground/$run': typeof PlaygroundRunRoute
  '/racer/$run': typeof RacerRunRoute
  '/api/adventure/voice': typeof ApiAdventureVoiceRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/github/contributions': typeof ApiGithubContributionsRoute
  '/.well-known/oauth-authorization-server/api/auth': typeof DotwellKnownOauthAuthorizationServerApiAuthRoute
  '/.well-known/oauth-protected-resource/api/mcp': typeof DotwellKnownOauthProtectedResourceApiMcpRoute
  '/api/auth/.well-known/openid-configuration': typeof ApiAuthDotwellKnownOpenidConfigurationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/adventure': typeof AdventureRouteWithChildren
  '/consent': typeof ConsentRoute
  '/doom': typeof DoomRoute
  '/guestbook': typeof GuestbookRoute
  '/me': typeof MeRoute
  '/now': typeof NowRoute
  '/os': typeof OsRoute
  '/playground': typeof PlaygroundRouteWithChildren
  '/racer': typeof RacerRouteWithChildren
  '/resume': typeof ResumeRoute
  '/terminal': typeof TerminalRoute
  '/.well-known/oauth-authorization-server': typeof DotwellKnownOauthAuthorizationServerRouteWithChildren
  '/.well-known/openid-configuration': typeof DotwellKnownOpenidConfigurationRoute
  '/adventure/$id': typeof AdventureIdRoute
  '/api/adventure': typeof ApiAdventureRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/api/guestbook': typeof ApiGuestbookRoute
  '/api/mcp': typeof ApiMcpRoute
  '/api/resume': typeof ApiResumeRoute
  '/ingest/$': typeof IngestSplatRoute
  '/playground/$run': typeof PlaygroundRunRoute
  '/racer/$run': typeof RacerRunRoute
  '/api/adventure/voice': typeof ApiAdventureVoiceRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/github/contributions': typeof ApiGithubContributionsRoute
  '/.well-known/oauth-authorization-server/api/auth': typeof DotwellKnownOauthAuthorizationServerApiAuthRoute
  '/.well-known/oauth-protected-resource/api/mcp': typeof DotwellKnownOauthProtectedResourceApiMcpRoute
  '/api/auth/.well-known/openid-configuration': typeof ApiAuthDotwellKnownOpenidConfigurationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/adventure'
    | '/consent'
    | '/doom'
    | '/guestbook'
    | '/me'
    | '/now'
    | '/os'
    | '/playground'
    | '/racer'
    | '/resume'
    | '/terminal'
    | '/.well-known/oauth-authorization-server'
    | '/.well-known/openid-configuration'
    | '/adventure/$id'
    | '/api/adventure'
    | '/api/chat'
    | '/api/guestbook'
    | '/api/mcp'
    | '/api/resume'
    | '/ingest/$'
    | '/playground/$run'
    | '/racer/$run'
    | '/api/adventure/voice'
    | '/api/auth/$'
    | '/api/github/contributions'
    | '/.well-known/oauth-authorization-server/api/auth'
    | '/.well-known/oauth-protected-resource/api/mcp'
    | '/api/auth/.well-known/openid-configuration'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/adventure'
    | '/consent'
    | '/doom'
    | '/guestbook'
    | '/me'
    | '/now'
    | '/os'
    | '/playground'
    | '/racer'
    | '/resume'
    | '/terminal'
    | '/.well-known/oauth-authorization-server'
    | '/.well-known/openid-configuration'
    | '/adventure/$id'
    | '/api/adventure'
    | '/api/chat'
    | '/api/guestbook'
    | '/api/mcp'
    | '/api/resume'
    | '/ingest/$'
    | '/playground/$run'
    | '/racer/$run'
    | '/api/adventure/voice'
    | '/api/auth/$'
    | '/api/github/contributions'
    | '/.well-known/oauth-authorization-server/api/auth'
    | '/.well-known/oauth-protected-resource/api/mcp'
    | '/api/auth/.well-known/openid-configuration'
  id:
    | '__root__'
    | '/'
    | '/adventure'
    | '/consent'
    | '/doom'
    | '/guestbook'
    | '/me'
    | '/now'
    | '/os'
    | '/playground'
    | '/racer'
    | '/resume'
    | '/terminal'
    | '/.well-known/oauth-authorization-server'
    | '/.well-known/openid-configuration'
    | '/adventure/$id'
    | '/api/adventure'
    | '/api/chat'
    | '/api/guestbook'
    | '/api/mcp'
    | '/api/resume'
    | '/ingest/$'
    | '/playground/$run'
    | '/racer/$run'
    | '/api/adventure/voice'
    | '/api/auth/$'
    | '/api/github/contributions'
    | '/.well-known/oauth-authorization-server/api/auth'
    | '/.well-known/oauth-protected-resource/api/mcp'
    | '/api/auth/.well-known/openid-configuration'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdventureRoute: typeof AdventureRouteWithChildren
  ConsentRoute: typeof ConsentRoute
  DoomRoute: typeof DoomRoute
  GuestbookRoute: typeof GuestbookRoute
  MeRoute: typeof MeRoute
  NowRoute: typeof NowRoute
  OsRoute: typeof OsRoute
  PlaygroundRoute: typeof PlaygroundRouteWithChildren
  RacerRoute: typeof RacerRouteWithChildren
  ResumeRoute: typeof ResumeRoute
  TerminalRoute: typeof TerminalRoute
  DotwellKnownOauthAuthorizationServerRoute: typeof DotwellKnownOauthAuthorizationServerRouteWithChildren
  DotwellKnownOpenidConfigurationRoute: typeof DotwellKnownOpenidConfigurationRoute
  ApiAdventureRoute: typeof ApiAdventureRouteWithChildren
  ApiChatRoute: typeof ApiChatRoute
  ApiGuestbookRoute: typeof ApiGuestbookRoute
  ApiMcpRoute: typeof ApiMcpRoute
  ApiResumeRoute: typeof ApiResumeRoute
  IngestSplatRoute: typeof IngestSplatRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiGithubContributionsRoute: typeof ApiGithubContributionsRoute
  DotwellKnownOauthProtectedResourceApiMcpRoute: typeof DotwellKnownOauthProtectedResourceApiMcpRoute
  ApiAuthDotwellKnownOpenidConfigurationRoute: typeof ApiAuthDotwellKnownOpenidConfigurationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adventure': {
      id: '/adventure'
      path: '/adventure'
      fullPath: '/adventure'
      preLoaderRoute: typeof AdventureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consent': {
      id: '/consent'
      path: '/consent'
      fullPath: '/consent'
      preLoaderRoute: typeof ConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doom': {
      id: '/doom'
      path: '/doom'
      fullPath: '/doom'
      preLoaderRoute: typeof DoomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guestbook': {
      id: '/guestbook'
      path: '/guestbook'
      fullPath: '/guestbook'
      preLoaderRoute: typeof GuestbookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/now': {
      id: '/now'
      path: '/now'
      fullPath: '/now'
      preLoaderRoute: typeof NowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/os': {
      id: '/os'
      path: '/os'
      fullPath: '/os'
      preLoaderRoute: typeof OsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/racer': {
      id: '/racer'
      path: '/racer'
      fullPath: '/racer'
      preLoaderRoute: typeof RacerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume': {
      id: '/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof ResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terminal': {
      id: '/terminal'
      path: '/terminal'
      fullPath: '/terminal'
      preLoaderRoute: typeof TerminalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-authorization-server': {
      id: '/.well-known/oauth-authorization-server'
      path: '/.well-known/oauth-authorization-server'
      fullPath: '/.well-known/oauth-authorization-server'
      preLoaderRoute: typeof DotwellKnownOauthAuthorizationServerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/openid-configuration': {
      id: '/.well-known/openid-configuration'
      path: '/.well-known/openid-configuration'
      fullPath: '/.well-known/openid-configuration'
      preLoaderRoute: typeof DotwellKnownOpenidConfigurationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adventure/$id': {
      id: '/adventure/$id'
      path: '/$id'
      fullPath: '/adventure/$id'
      preLoaderRoute: typeof AdventureIdRouteImport
      parentRoute: typeof AdventureRoute
    }
    '/api/adventure': {
      id: '/api/adventure'
      path: '/api/adventure'
      fullPath: '/api/adventure'
      preLoaderRoute: typeof ApiAdventureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/guestbook': {
      id: '/api/guestbook'
      path: '/api/guestbook'
      fullPath: '/api/guestbook'
      preLoaderRoute: typeof ApiGuestbookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp': {
      id: '/api/mcp'
      path: '/api/mcp'
      fullPath: '/api/mcp'
      preLoaderRoute: typeof ApiMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/resume': {
      id: '/api/resume'
      path: '/api/resume'
      fullPath: '/api/resume'
      preLoaderRoute: typeof ApiResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingest/$': {
      id: '/ingest/$'
      path: '/ingest/$'
      fullPath: '/ingest/$'
      preLoaderRoute: typeof IngestSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground/$run': {
      id: '/playground/$run'
      path: '/$run'
      fullPath: '/playground/$run'
      preLoaderRoute: typeof PlaygroundRunRouteImport
      parentRoute: typeof PlaygroundRoute
    }
    '/racer/$run': {
      id: '/racer/$run'
      path: '/$run'
      fullPath: '/racer/$run'
      preLoaderRoute: typeof RacerRunRouteImport
      parentRoute: typeof RacerRoute
    }
    '/api/adventure/voice': {
      id: '/api/adventure/voice'
      path: '/voice'
      fullPath: '/api/adventure/voice'
      preLoaderRoute: typeof ApiAdventureVoiceRouteImport
      parentRoute: typeof ApiAdventureRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/contributions': {
      id: '/api/github/contributions'
      path: '/api/github/contributions'
      fullPath: '/api/github/contributions'
      preLoaderRoute: typeof ApiGithubContributionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-authorization-server/api/auth': {
      id: '/.well-known/oauth-authorization-server/api/auth'
      path: '/api/auth'
      fullPath: '/.well-known/oauth-authorization-server/api/auth'
      preLoaderRoute: typeof DotwellKnownOauthAuthorizationServerApiAuthRouteImport
      parentRoute: typeof DotwellKnownOauthAuthorizationServerRoute
    }
    '/.well-known/oauth-protected-resource/api/mcp': {
      id: '/.well-known/oauth-protected-resource/api/mcp'
      path: '/.well-known/oauth-protected-resource/api/mcp'
      fullPath: '/.well-known/oauth-protected-resource/api/mcp'
      preLoaderRoute: typeof DotwellKnownOauthProtectedResourceApiMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/.well-known/openid-configuration': {
      id: '/api/auth/.well-known/openid-configuration'
      path: '/api/auth/.well-known/openid-configuration'
      fullPath: '/api/auth/.well-known/openid-configuration'
      preLoaderRoute: typeof ApiAuthDotwellKnownOpenidConfigurationRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdventureRouteChildren {
  AdventureIdRoute: typeof AdventureIdRoute
}

const AdventureRouteChildren: AdventureRouteChildren = {
  AdventureIdRoute: AdventureIdRoute,
}

const AdventureRouteWithChildren = AdventureRoute._addFileChildren(
  AdventureRouteChildren,
)

interface PlaygroundRouteChildren {
  PlaygroundRunRoute: typeof PlaygroundRunRoute
}

const PlaygroundRouteChildren: PlaygroundRouteChildren = {
  PlaygroundRunRoute: PlaygroundRunRoute,
}

const PlaygroundRouteWithChildren = PlaygroundRoute._addFileChildren(
  PlaygroundRouteChildren,
)

interface RacerRouteChildren {
  RacerRunRoute: typeof RacerRunRoute
}

const RacerRouteChildren: RacerRouteChildren = {
  RacerRunRoute: RacerRunRoute,
}

const RacerRouteWithChildren = RacerRoute._addFileChildren(RacerRouteChildren)

interface DotwellKnownOauthAuthorizationServerRouteChildren {
  DotwellKnownOauthAuthorizationServerApiAuthRoute: typeof DotwellKnownOauthAuthorizationServerApiAuthRoute
}

const DotwellKnownOauthAuthorizationServerRouteChildren: DotwellKnownOauthAuthorizationServerRouteChildren =
  {
    DotwellKnownOauthAuthorizationServerApiAuthRoute:
      DotwellKnownOauthAuthorizationServerApiAuthRoute,
  }

const DotwellKnownOauthAuthorizationServerRouteWithChildren =
  DotwellKnownOauthAuthorizationServerRoute._addFileChildren(
    DotwellKnownOauthAuthorizationServerRouteChildren,
  )

interface ApiAdventureRouteChildren {
  ApiAdventureVoiceRoute: typeof ApiAdventureVoiceRoute
}

const ApiAdventureRouteChildren: ApiAdventureRouteChildren = {
  ApiAdventureVoiceRoute: ApiAdventureVoiceRoute,
}

const ApiAdventureRouteWithChildren = ApiAdventureRoute._addFileChildren(
  ApiAdventureRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdventureRoute: AdventureRouteWithChildren,
  ConsentRoute: ConsentRoute,
  DoomRoute: DoomRoute,
  GuestbookRoute: GuestbookRoute,
  MeRoute: MeRoute,
  NowRoute: NowRoute,
  OsRoute: OsRoute,
  PlaygroundRoute: PlaygroundRouteWithChildren,
  RacerRoute: RacerRouteWithChildren,
  ResumeRoute: ResumeRoute,
  TerminalRoute: TerminalRoute,
  DotwellKnownOauthAuthorizationServerRoute:
    DotwellKnownOauthAuthorizationServerRouteWithChildren,
  DotwellKnownOpenidConfigurationRoute: DotwellKnownOpenidConfigurationRoute,
  ApiAdventureRoute: ApiAdventureRouteWithChildren,
  ApiChatRoute: ApiChatRoute,
  ApiGuestbookRoute: ApiGuestbookRoute,
  ApiMcpRoute: ApiMcpRoute,
  ApiResumeRoute: ApiResumeRoute,
  IngestSplatRoute: IngestSplatRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiGithubContributionsRoute: ApiGithubContributionsRoute,
  DotwellKnownOauthProtectedResourceApiMcpRoute:
    DotwellKnownOauthProtectedResourceApiMcpRoute,
  ApiAuthDotwellKnownOpenidConfigurationRoute:
    ApiAuthDotwellKnownOpenidConfigurationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
